import { ApiResponseOptions } from "@nestjs/swagger";

export const GetPeakPlateResponse: ApiResponseOptions = {
  status: 200,
  description:
    "Returns the peak plate restrictions for the specified city, plate, year and month",
  schema: {
    example: {
      city: "bogota",
      plate: "CXR217",
      year: 2025,
      month: 3,
      dailyRestrictions: [
        { day: 1, status: false },
        { day: 2, status: false },
        { day: 3, status: false },
        { day: 4, status: false },
        { day: 5, status: false },
        { day: 6, status: false },
        { day: 7, status: false },
        { day: 8, status: false },
        { day: 9, status: false },
        { day: 10, status: false },
        { day: 11, status: false },
        { day: 12, status: false },
        { day: 13, status: false },
        { day: 14, status: false },
        { day: 15, status: false },
        { day: 16, status: false },
        { day: 17, status: false },
        { day: 18, status: false },
        { day: 19, status: true },
        { day: 20, status: false },
        { day: 21, status: true },
        { day: 22, status: false },
        { day: 23, status: false },
        { day: 24, status: true },
        { day: 25, status: true },
        { day: 26, status: false },
        { day: 27, status: true },
        { day: 28, status: false },
        { day: 29, status: false },
        { day: 30, status: false },
        { day: 31, status: true },
      ],
      id: 2,
      hours: null,
    },
  },
};
